language: node_js
node_js:
  - "0.10"
env:
  global:
   - GH_REF=github.com/applicaster/siren-browser.git
   - secure: Kfq+4RB4vfTrG0Q1s6XlW2tN/YQZ0pP72NkWIRrxYWedXDwkRK51gk12pLpmVfPOKPAoFmS/5uUXYCvS+u1pf5IbHwQjBAgNIgmPkYfodKceIyAFNi/nnibu+XpODapGuEnCXEwIE1UfE2phBItuFxSeQovmHc7hR7+D4206zUA=
before_install:
  - "npm install -g bower"
  - "npm install -g gulp"
  - "bower install"
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - npm install
  - bower install
  - gulp build
  - chmod a+x ./scripts/gh-pages-deploy.sh
  - ./scripts/gh-pages-deploy.sh
